//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using ProyectoAMBE.Data;

//#nullable disable

//namespace ProyectoAMBE.Migrations
//{
//    [DbContext(typeof(AmbedbContext))]
//    partial class AmbedbContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.2")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("ProyectoAMBE.Data.Bitacora", b =>
//                {
//                    b.Property<int>("IdBitacora")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("ID_BITACORA");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBitacora"));

//                    b.Property<DateTime?>("Fecha")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<int>("IdInstituto")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_INSTITUTO");

//                    b.Property<int>("IdUsuario")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_USUARIO");

//                    b.Property<string>("Tabla")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("TABLA");

//                    b.Property<string>("TipoAccion")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("TIPO_ACCION");

//                    b.HasKey("IdBitacora")
//                        .HasName("PK__BITACORA__44E70BF3E55560D2");

//                    b.ToTable("BITACORA", (string)null);
//                });

//            modelBuilder.Entity("ProyectoAMBE.Data.InstitutoRoles", b =>
//                {
//                    b.Property<int>("IdInstitutoRol")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("ID_INSTITUTO_ROL");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInstitutoRol"));

//                    b.Property<int>("IdInstituto")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_INSTITUTO");

//                    b.Property<int>("IdRol")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_ROL");

//                    b.HasKey("IdInstitutoRol")
//                        .HasName("PK__INSTITUT__F48D85DCA89AB471");

//                    b.ToTable("INSTITUTO_ROLES", (string)null);
//                });

//            modelBuilder.Entity("ProyectoAMBE.Data.InstitutoUsuarios", b =>
//                {
//                    b.Property<int>("IdInstitutoUsuario")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("ID_INSTITUTO_USUARIO");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInstitutoUsuario"));

//                    b.Property<int>("IdInstituto")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_INSTITUTO");

//                    b.Property<int>("IdUsuario")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_USUARIO");

//                    b.HasKey("IdInstitutoUsuario")
//                        .HasName("PK__INSTITUT__74FAE9E1B152300B");

//                    b.ToTable("INSTITUTO_USUARIOS", (string)null);
//                });

//            modelBuilder.Entity("ProyectoAMBE.Data.Institutos", b =>
//                {
//                    b.Property<int>("IdInstituto")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("ID_INSTITUTO");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInstituto"));

//                    b.Property<string>("CreadoPor")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("CREADO_POR");

//                    b.Property<string>("Descripcion")
//                        .HasMaxLength(200)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(200)")
//                        .HasColumnName("DESCRIPCION");

//                    b.Property<string>("Direccion")
//                        .HasMaxLength(100)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(100)")
//                        .HasColumnName("DIRECCION");

//                    b.Property<string>("Email")
//                        .HasMaxLength(25)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(25)")
//                        .HasColumnName("EMAIL");

//                    b.Property<DateTime?>("FechaCreacion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_CREACION")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<DateTime?>("FechaModificacion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_MODIFICACION")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<string>("ModificadoPor")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("MODIFICADO_POR");

//                    b.Property<string>("NombreInstituto")
//                        .HasMaxLength(100)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(100)")
//                        .HasColumnName("NOMBRE_INSTITUTO");

//                    b.Property<string>("Rtn")
//                        .HasMaxLength(20)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(20)")
//                        .HasColumnName("RTN");

//                    b.Property<string>("Telefono")
//                        .HasMaxLength(15)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(15)")
//                        .HasColumnName("TELEFONO");

//                    b.HasKey("IdInstituto")
//                        .HasName("PK__INSTITUT__E031A83A11780ADE");

//                    b.ToTable("INSTITUTOS", (string)null);
//                });

//            modelBuilder.Entity("ProyectoAMBE.Data.Objetos", b =>
//                {
//                    b.Property<int>("IdObjeto")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("ID_OBJETO");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObjeto"));

//                    b.Property<string>("CreadoPor")
//                        .HasMaxLength(100)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(100)")
//                        .HasColumnName("CREADO_POR");

//                    b.Property<string>("Descripcion")
//                        .HasColumnType("text")
//                        .HasColumnName("DESCRIPCION");

//                    b.Property<DateTime?>("FechaDeCreacion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_DE_CREACION")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<DateTime?>("FechaDeModificacion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_DE_MODIFICACION")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<int?>("IdInstituto")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_INSTITUTO");

//                    b.Property<string>("ModificadoPor")
//                        .HasMaxLength(100)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(100)")
//                        .HasColumnName("MODIFICADO_POR");

//                    b.Property<string>("Objeto")
//                        .HasMaxLength(255)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(255)")
//                        .HasColumnName("OBJETO");

//                    b.Property<string>("TipoObjeto")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("TIPO_OBJETO");

//                    b.HasKey("IdObjeto")
//                        .HasName("PK__OBJETOS__6F0599673335FDC3");

//                    b.ToTable("OBJETOS", (string)null);
//                });

//            modelBuilder.Entity("ProyectoAMBE.Data.Parametros", b =>
//                {
//                    b.Property<int>("IdParametro")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("ID_PARAMETRO");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParametro"));

//                    b.Property<int>("IdUsuario")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_USUARIO");

//                    b.Property<string>("Parametro")
//                        .HasMaxLength(10)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(10)")
//                        .HasColumnName("PARAMETRO");

//                    b.Property<string>("Valor")
//                        .HasMaxLength(10)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(10)")
//                        .HasColumnName("VALOR");

//                    b.HasKey("IdParametro")
//                        .HasName("PK__PARAMETR__79032FF56F779CB9");

//                    b.ToTable("PARAMETROS", (string)null);
//                });

//            modelBuilder.Entity("ProyectoAMBE.Data.Permisos", b =>
//                {
//                    b.Property<int>("IdPermiso")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("ID_PERMISO");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

//                    b.Property<DateTime?>("FechaCreacion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_CREACION")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<DateTime?>("FechaModificacion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_MODIFICACION")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<int>("IdInstituto")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_INSTITUTO");

//                    b.Property<int>("IdObjeto")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_OBJETO");

//                    b.Property<int>("IdRol")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_ROL");

//                    b.Property<string>("ModificadoPor")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("MODIFICADO_POR");

//                    b.Property<string>("Permiso")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("PERMISO");

//                    b.HasKey("IdPermiso")
//                        .HasName("PK__PERMISOS__AC74EBF6D7F3647B");

//                    b.ToTable("PERMISOS", (string)null);
//                });

//            modelBuilder.Entity("ProyectoAMBE.Data.Personas", b =>
//                {
//                    b.Property<int>("IdPersona")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("ID_PERSONA");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

//                    b.Property<string>("CreadoPor")
//                        .HasMaxLength(100)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(100)")
//                        .HasColumnName("CREADO_POR");

//                    b.Property<string>("Estado")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("ESTADO");

//                    b.Property<DateTime?>("FechaCreacion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_CREACION")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<DateTime?>("FechaModificacion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_MODIFICACION")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<DateTime?>("FechaNacimiento")
//                        .HasColumnType("datetime2")
//                        .HasColumnName("FECHA_NACIMIENTO");

//                    b.Property<string>("Genero")
//                        .HasMaxLength(20)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(20)")
//                        .HasColumnName("GENERO");

//                    b.Property<int>("IdInstituto")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_INSTITUTO");

//                    b.Property<int>("IdTipoPersona")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_TIPO_PERSONA");

//                    b.Property<string>("ModificadoPor")
//                        .HasMaxLength(100)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(100)")
//                        .HasColumnName("MODIFICADO_POR");

//                    b.Property<string>("PrimerApellido")
//                        .HasMaxLength(40)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(40)")
//                        .HasColumnName("PRIMER_APELLIDO");

//                    b.Property<string>("PrimerNombre")
//                        .HasMaxLength(40)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(40)")
//                        .HasColumnName("PRIMER_NOMBRE");

//                    b.Property<string>("SegundoApellido")
//                        .HasMaxLength(40)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(40)")
//                        .HasColumnName("SEGUNDO_APELLIDO");

//                    b.Property<string>("SegundoNombre")
//                        .HasMaxLength(40)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(40)")
//                        .HasColumnName("SEGUNDO_NOMBRE");

//                    b.HasKey("IdPersona")
//                        .HasName("PK__PERSONAS__78244149A2CB5E92");

//                    b.ToTable("PERSONAS", (string)null);
//                });

//            modelBuilder.Entity("ProyectoAMBE.Data.Roles", b =>
//                {
//                    b.Property<int>("IdRol")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("ID_ROL");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

//                    b.Property<string>("CreadoPor")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("CREADO_POR");

//                    b.Property<string>("Descripcion")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("DESCRIPCION");

//                    b.Property<DateTime>("FechaCreacion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_CREACION")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<DateTime>("FechaModificacion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_MODIFICACION")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<int>("IdInstituto")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_INSTITUTO");

//                    b.Property<string>("ModificadoPor")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("MODIFICADO_POR");

//                    b.HasKey("IdRol")
//                        .HasName("PK__ROLES__203B0F68D2C5EC61");

//                    b.ToTable("ROLES", (string)null);
//                });

//            modelBuilder.Entity("ProyectoAMBE.Data.TipoPersonas", b =>
//                {
//                    b.Property<int>("IdTipoPersona")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("ID_TIPO_PERSONA");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoPersona"));

//                    b.Property<string>("CreadoPor")
//                        .HasMaxLength(100)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(100)")
//                        .HasColumnName("CREADO_POR");

//                    b.Property<string>("Descripcion")
//                        .HasMaxLength(80)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(80)")
//                        .HasColumnName("DESCRIPCION");

//                    b.Property<string>("Estado")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("ESTADO");

//                    b.Property<DateTime?>("FechaCreacion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_CREACION")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<DateTime?>("FechaModificacion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_MODIFICACION")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<int>("IdInstituto")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_INSTITUTO");

//                    b.Property<string>("ModificadoPor")
//                        .HasMaxLength(100)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(100)")
//                        .HasColumnName("MODIFICADO_POR");

//                    b.Property<string>("TipoPersona")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("TIPO_PERSONA");

//                    b.HasKey("IdTipoPersona")
//                        .HasName("PK__TIPO_PER__E007574A71D77A60");

//                    b.ToTable("TIPO_PERSONAS", (string)null);
//                });

//            modelBuilder.Entity("ProyectoAMBE.Data.Usuarios", b =>
//                {
//                    b.Property<int>("IdUsuario")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("ID_USUARIO");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

//                    b.Property<string>("Contraseña")
//                        .HasMaxLength(20)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(20)")
//                        .HasColumnName("CONTRASEÑA");

//                    b.Property<string>("CorreoElectronico")
//                        .HasMaxLength(100)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(100)")
//                        .HasColumnName("CORREO_ELECTRONICO");

//                    b.Property<string>("CreadoPor")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("CREADO_POR");

//                    b.Property<string>("Estado")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("ESTADO");

//                    b.Property<DateTime?>("FechaCreacion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_CREACION")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<DateTime?>("FechaModificacion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_MODIFICACION")
//                        .HasDefaultValueSql("(getdate())");

//                    b.Property<DateTime?>("FechaUltimaConexion")
//                        .HasColumnType("datetime")
//                        .HasColumnName("FECHA_ULTIMA_CONEXION");

//                    b.Property<int?>("IdInstituto")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_INSTITUTO");

//                    b.Property<int?>("IdPersona")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_PERSONA");

//                    b.Property<int?>("IdRol")
//                        .HasColumnType("int")
//                        .HasColumnName("ID_ROL");

//                    b.Property<string>("ModificadoPor")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("MODIFICADO_POR");

//                    b.Property<string>("NombreUsuario")
//                        .HasMaxLength(100)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(100)")
//                        .HasColumnName("NOMBRE_USUARIO");

//                    b.Property<string>("Usuario")
//                        .HasMaxLength(50)
//                        .IsUnicode(false)
//                        .HasColumnType("varchar(50)")
//                        .HasColumnName("USUARIO");

//                    b.HasKey("IdUsuario")
//                        .HasName("PK__USUARIOS__91136B90BDB3BB42");

//                    b.ToTable("USUARIOS", (string)null);
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
